//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorCorps
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DoctorCorpsEntities : DbContext
    {
        public DoctorCorpsEntities()
            : base("name=DoctorCorpsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AppointmentsTable> AppointmentsTable { get; set; }
        public virtual DbSet<DoctorTable> DoctorTable { get; set; }
        public virtual DbSet<HospitalRatingTable> HospitalRatingTable { get; set; }
        public virtual DbSet<HospitalTable> HospitalTable { get; set; }
        public virtual DbSet<PathologyTable> PathologyTable { get; set; }
        public virtual DbSet<PreviousAppointmentsTable> PreviousAppointmentsTable { get; set; }
        public virtual DbSet<ReportTable> ReportTable { get; set; }
        public virtual DbSet<ServiceTable> ServiceTable { get; set; }
        public virtual DbSet<UserTable> UserTable { get; set; }
    }
}
