//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorCorps
{
    using System;
    using System.Collections.Generic;
    
    public partial class HospitalServiceTable
    {
        public int HSID { get; set; }
        public int HospitalID { get; set; }
        public int ServiceID { get; set; }
    
        public virtual HospitalTable HospitalTable { get; set; }
        public virtual ServiceTable ServiceTable { get; set; }
    }
}
