//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorCorps
{
    using System;
    using System.Collections.Generic;
    
    public partial class PathologyTable
    {
        public int PathologyID { get; set; }
        public string PathologyName { get; set; }
        public int PathologyFees { get; set; }
        public string PatholgyDescription { get; set; }
        public Nullable<int> DoctorID { get; set; }
        public Nullable<int> HospitalID { get; set; }
        public string PathologyLocation { get; set; }
    
        public virtual DoctorTable DoctorTable { get; set; }
        public virtual HospitalTable HospitalTable { get; set; }
    }
}
